service: employee-portal-service
provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  environment:
    EMPLOYEE_TABLE: ${self:custom.employeeTableName}
    REGION: !Ref AWS::Region
custom:
  employeeTableName: employee-Details-${self:provider.stage}
plugins:
  - serverless-iam-roles-per-function
functions:
  employeeGet:
    handler: src/Lamda/employee/employeeHandler.employee
    name: getEmployeeDetails
    memorySize: 512
    timeout: 120
    events:
      - http:
          path: employee/{empId}
          method: GET
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:PutItem"
          - "dynamodb:UpdateItem"
          - "dynamodb:GetItem"
          - "dynamodb:Scan"
          - "dynamodb:DeleteItem"
        Resource:
          - !GetAtt ${self:custom.employeeTableName}.Arn

resources:
  Resources:
    EmployeeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.employeeTable}
        AttributeDefinitions:
          - AttributeName: empId
            AttributeType: S
        KeySchema:
          - AttributeName: empId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        